### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by C3604** [hormones/submission_telebot#1]
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import commands
  File "/TGBOT/submission_telebot/commands/__init__.py", line 3, in <module>
    from . import __common__, ban, feedback, help, lang, reply, setting
  File "/TGBOT/submission_telebot/commands/__common__.py", line 8, in <module>
    import config
  File "/TGBOT/submission_telebot/config.py", line 17, in <module>
    USER_COMMAND_KEYS: list[str] = util.get_config(__config, 'user_commands', ["start", "lang", "help"])
TypeError: 'type' object is not subscriptable
```

**Comment by hormones** [comment]
大概率是python版本的问题，我测试的时候用的是3.10.6，你可以尝试升级python版本再试试呢，我再完善下文档，写明python版本要求~

**Comment by hormones** [comment]
已经降级python可支持的版本，最低支持3.7.3
